<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4fGzTZh' shared service.

return $this->privates['.service_locator.4fGzTZh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'booking' => ['privates', '.errored..service_locator.4fGzTZh.App\\Entity\\Booking', NULL, 'Cannot autowire service ".service_locator.4fGzTZh": it references class "App\\Entity\\Booking" but no such service exists.'],
], [
    'booking' => 'App\\Entity\\Booking',
]);
