<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\ApplicationType' shared autowired service.

return $this->privates['App\\Form\\ApplicationType'] = new \App\Form\ApplicationType();
