<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.command.debug' shared service.

$this->privates['twig.command.debug'] = $instance = new \Symfony\Bridge\Twig\Command\DebugCommand(($this->services['twig'] ?? $this->getTwigService()), 'C:\\projet-symfony-RR', $this->parameters['kernel.bundles_metadata'], 'C:\\projet-symfony-RR/templates', ($this->privates['debug.file_link_formatter'] ?? $this->getDebug_FileLinkFormatterService()), 'C:\\projet-symfony-RR\\src');

$instance->setName('debug:twig');

return $instance;
