<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.template_cache_warmer' shared service.

return $this->privates['twig.template_cache_warmer'] = new \Symfony\Bundle\TwigBundle\CacheWarmer\TemplateCacheWarmer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'twig' => ['services', 'twig', 'getTwigService', false],
], [
    'twig' => 'Twig\\Environment',
]))->withContext('twig.template_cache_warmer', $this), new \Symfony\Bundle\TwigBundle\TemplateIterator(($this->services['kernel'] ?? $this->get('kernel', 1)), 'C:\\projet-symfony-RR\\src', ['C:\\projet-symfony-RR/templates' => NULL, 'C:\\projet-symfony-RR\\vendor\\symfony\\twig-bridge/Resources/views/Email' => 'email', 'C:\\projet-symfony-RR\\vendor\\symfony\\twig-bridge/Resources/views/Form' => NULL], 'C:\\projet-symfony-RR/templates'));
