<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.YCze_gN' shared service.

return $this->privates['.service_locator.YCze_gN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AccountController::login' => ['privates', '.service_locator.Z9YHLOP', 'get_ServiceLocator_Z9YHLOPService.php', true],
    'App\\Controller\\AccountController::register' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\AdController::index' => ['privates', '.service_locator.0rLqTXE', 'get_ServiceLocator_0rLqTXEService.php', true],
    'App\\Controller\\AdController::show' => ['privates', '.service_locator.RCKhk5j', 'get_ServiceLocator_RCKhk5jService.php', true],
    'App\\Controller\\BookingController::book' => ['privates', '.service_locator.RCKhk5j', 'get_ServiceLocator_RCKhk5jService.php', true],
    'App\\Controller\\BookingController::show' => ['privates', '.service_locator.4fGzTZh', 'get_ServiceLocator_4fGzTZhService.php', true],
    'App\\Controller\\HomeController::home' => ['privates', '.service_locator.ODfGc_j', 'get_ServiceLocator_ODfGcJService.php', true],
    'App\\Controller\\UserController::index' => ['privates', '.service_locator.tIQ5Q0N', 'get_ServiceLocator_TIQ5Q0NService.php', true],
    'App\\Controller\\AccountController:login' => ['privates', '.service_locator.Z9YHLOP', 'get_ServiceLocator_Z9YHLOPService.php', true],
    'App\\Controller\\AccountController:register' => ['privates', '.service_locator.jmvbEvf', 'get_ServiceLocator_JmvbEvfService.php', true],
    'App\\Controller\\AdController:index' => ['privates', '.service_locator.0rLqTXE', 'get_ServiceLocator_0rLqTXEService.php', true],
    'App\\Controller\\AdController:show' => ['privates', '.service_locator.RCKhk5j', 'get_ServiceLocator_RCKhk5jService.php', true],
    'App\\Controller\\BookingController:book' => ['privates', '.service_locator.RCKhk5j', 'get_ServiceLocator_RCKhk5jService.php', true],
    'App\\Controller\\BookingController:show' => ['privates', '.service_locator.4fGzTZh', 'get_ServiceLocator_4fGzTZhService.php', true],
    'App\\Controller\\HomeController:home' => ['privates', '.service_locator.ODfGc_j', 'get_ServiceLocator_ODfGcJService.php', true],
    'App\\Controller\\UserController:index' => ['privates', '.service_locator.tIQ5Q0N', 'get_ServiceLocator_TIQ5Q0NService.php', true],
], [
    'App\\Controller\\AccountController::login' => '?',
    'App\\Controller\\AccountController::register' => '?',
    'App\\Controller\\AdController::index' => '?',
    'App\\Controller\\AdController::show' => '?',
    'App\\Controller\\BookingController::book' => '?',
    'App\\Controller\\BookingController::show' => '?',
    'App\\Controller\\HomeController::home' => '?',
    'App\\Controller\\UserController::index' => '?',
    'App\\Controller\\AccountController:login' => '?',
    'App\\Controller\\AccountController:register' => '?',
    'App\\Controller\\AdController:index' => '?',
    'App\\Controller\\AdController:show' => '?',
    'App\\Controller\\BookingController:book' => '?',
    'App\\Controller\\BookingController:show' => '?',
    'App\\Controller\\HomeController:home' => '?',
    'App\\Controller\\UserController:index' => '?',
]);
