<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.m1RiI2J' shared service.

return $this->privates['.service_locator.m1RiI2J'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('repo' => function (): \App\Repository\AdRepository {
    return ($this->privates['App\Repository\AdRepository'] ?? $this->load('getAdRepositoryService.php'));
}));
