<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.G6.Ck59' shared service.

return $this->privates['.service_locator.G6.Ck59'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('adRepo' => function (): \App\Repository\AdRepository {
    return ($this->privates['App\Repository\AdRepository'] ?? $this->load('getAdRepositoryService.php'));
}, 'userRepo' => function (): \App\Repository\UserRepository {
    return ($this->privates['App\Repository\UserRepository'] ?? $this->load('getUserRepositoryService.php'));
}));
