<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tiwWAIk' shared service.

return $this->privates['.service_locator.tiwWAIk'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('pagination' => function (): \App\Service\PaginationService {
    return ($this->privates['App\Service\PaginationService'] ?? $this->load('getPaginationServiceService.php'));
}, 'repo' => function (): \App\Repository\BookingRepository {
    return ($this->privates['App\Repository\BookingRepository'] ?? $this->load('getBookingRepositoryService.php'));
}));
