<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.fBcpXpI' shared service.

return $this->privates['.service_locator.fBcpXpI'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('ad' => function (): \App\Entity\Ad {
    return ($this->privates['.errored..service_locator.fBcpXpI.App\Entity\Ad'] ?? $this->load('getAd2Service.php'));
}));
