<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\AdminAdController' shared autowired service.

return $this->services['App\Controller\AdminAdController'] = new \App\Controller\AdminAdController();
