<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.A1S0c55.App\Entity\Ad' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.A1S0c55": it references class "App\\Entity\\Ad" but no such service exists.');
