<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.Utf_kyb.App\Entity\Comment' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.Utf_kyb": it references class "App\\Entity\\Comment" but no such service exists.');
