<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Repository\PasswordUpdateRepository' shared autowired service.

return $this->privates['App\Repository\PasswordUpdateRepository'] = new \App\Repository\PasswordUpdateRepository(($this->services['doctrine'] ?? $this->getDoctrineService()));
