<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKj9X0zK\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKj9X0zK/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKj9X0zK.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKj9X0zK\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKj9X0zK\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Kj9X0zK',
    'container.build_id' => 'b5b207d4',
    'container.build_time' => 1578566449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKj9X0zK');
