<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7xOUxFv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7xOUxFv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7xOUxFv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7xOUxFv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container7xOUxFv\srcDevDebugProjectContainer(array(
    'container.build_hash' => '7xOUxFv',
    'container.build_id' => 'a0f62dfa',
    'container.build_time' => 1577743366,
), __DIR__.\DIRECTORY_SEPARATOR.'Container7xOUxFv');
